slides:
    first:
        text: Have you ever seen <a href="https://github.com/bartaz/impress.js">Impress.js</a>?
    amazing:
        text: Have you seen how awesome it is?
        data:
            x: 1000
    you_can_do_it:
        text: And do you know that you can create your own slider easily?
        data:
            x: 2000
    movement_3d:
        text: With 3D movement...
        data:
            x: 0
            y: 1500
            z: 1050
            rotate-x: -45
            rotate-y: -45
    before_overview:
        text: And overview (see next slide).
        data:
            z: 7000
    overview:
        data:
            x: 1000
            z: 10000
    yml:
        text: Based on a simple <code>YAML</code> file...
        data:
            x: 1000
            z: 10000
            y: 1000
    download:
        attr:
            style: "text-shadow: 0 0 10px #000, 0 0 10px #000;"
        text: Download it on <a href="https://github.com/Orbitale/EasyImpress">Github</a>
        data:
            x: 1000
            y: 1000
            z: 11000

config:
    inactive_opacity: 1
    data:
        transition-duration: 1000
        min-scale: 1
    attr:
        style: "width: 100%;height: 100%;"

